version: 2

sources:
  - name: public
    tables:
      - name: employees
        description: "Real table with employee information"

models:
  - name: employees_resume
    description: >
      Summary of employee data grouped by gender, department, and job title.
      Includes calculated fields such as estimated age, working years, and employee status.
    columns:
      - name: gender
        description: Gender of the employee.
      - name: department
        description: Department the employee belongs to.
      - name: job_title
        description: Job title held by the employee.
      - name: employees
        description: Total number of employees in the grouped combination of gender, department, job title, and status.
      - name: age
        description: Estimated age calculated as the difference between current year and birth year.
      - name: working_years
        description: Estimated number of years worked based on hire and termination dates.
      - name: status
        description: Employment status (e.g., ACTIVE or TERMINATED).