version: 2

sources:
  - name: public
    tables:
      - name: employees
        description: "Real table with employee information"

models:
  - name: terminated_employees_by_department
    description: "Number of terminated employees by department"
    columns:
      - name: department
        description: "Department"
      - name: employees
        description: "Number of terminated employees"
