transformations_postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: admin123
      port: 5432
      dbname: postgres
      schema: public 
      threads: 2

transformations_bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: thinking-star-427923-v6
      dataset: employees
      keyfile: /home/camilajaviera/gcloud/auth.json
      threads: 2
