version: 2

sources:
  - name: public
    tables:
      - name: employees
        description: "Real table with employee information"

models:
  - name: dept_exits
    description: "Number of terminated employees by department"
    columns:
      - name: department
        description: "Department"
      - name: employees
        description: "Number of terminated employees"
    
  - name: dept_turnover
    description: "Department-level summary of employee count, terminations, and turnover rate"
    columns:
      - name: department
        description: "Department name"
      - name: employees
        description: "Total number of employees"
      - name: terminated
        description: "Number of employees who have left"
      - name: active_employees
        description: "Current number of active employees"
      - name: turnover_rate
        description: "Termination rate per department"
  
  - name: staff_changes
    description: "Annual summary of hires and terminations by department"
    columns:
      - name: year
        description: "Year based on hire or termination date"
      - name: department
        description: "Department name"
      - name: hired_count
        description: "Number of hires in the year"
      - name: terminated_count
        description: "Number of terminations in the year"

  - name: employees_resume
    description: >
      Summary of employee data grouped by gender, department, and job title.
      Includes calculated fields such as estimated age, working years, and employee status.
    columns:
      - name: gender
        description: Gender of the employee.
        tests:
          - not_null

      - name: department
        description: Department the employee belongs to.
        tests:
          - not_null

      - name: job_title
        description: Job title held by the employee.
        tests:
          - not_null

      - name: employees
        description: Total number of employees in the grouped combination of gender, department, job title, and status.
        tests:
          - not_null
          - numeric_bounds:
              min: 1

      - name: age
        description: Estimated age calculated as the difference between current year and birth year.
        tests:
          - not_null
          - expression_is_true:
              expression: "age >= 15"

      - name: working_years
        description: Estimated number of years worked based on hire and termination dates.
        tests:
          - not_null
          - expression_is_true:
              expression: "working_years >= 0"

      - name: status
        description: Employment status (e.g., ACTIVE or TERMINATED).
        tests:
          - not_null
          - accepted_values:
              values: ['ACTIVE', 'TERMINATED']