transformations_bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: thinking-star-427923-v6.employees
      dataset: employees
      keyfile: /home/camilajaviera/gcloud/auth.json
      threads: 2
